Map the model class (Pydantic )with the ORM class.
This required a hack adding __pydantic_private__ which is pending to investigate why Pydantic fails here. If we remove it, the error is:

AttributeError: 'EBPFProgram' object has no attribute '__pydantic_private__'. Did you mean: '__pydantic_complete__'?

Which comes from: https://github.com/pydantic/pydantic/blame/cdca7aebba33770416c260335e914c1755c48f13/pydantic/main.py#L850

Also, pending to investigate why SQLAchemy does not respect the order attributes of the entites passed when we query with session.query